### ISSUE TITLE
Visualizing structures

### ISSUE THREAD

**Issue by jessakay** [anyuzx/HIPPS-DIMES#1]
Thanks for make your method so accessible! It was a breeze to run and your paper was really clear and helpful for me to compute metrics such as F(k) or Q(k). But I'm having some trouble plotting the output structures described in the `xyz` file, as I'm not so familiar with molecular visualization. Would you mind sharing the script (PyMOL? VMD?) used to generate the 3D structures in your paper? Figure 4 (a) for example.

**Comment by anyuzx** [comment]
hello, the generated `.xyz` file should be directly compatible with VMD. Could you send the xyz file so that I can have a look at. Also, in the end of this jupyter notebook https://github.com/anyuzx/HIPPS-DIMES/blob/main/walkthrough.ipynb, there is a screen record for showing how to load the .xyz into VMD. Thanks.

**Comment by jessakay** [comment]
Sorry that I missed your reply. Please find attached an example xyz file.
[ESC.chr1.1.xyz.zip](https://github.com/anyuzx/HIPPS-DIMES/files/6446858/ESC.chr1.1.xyz.zip)

I'm hoping to in the end produce something similar to the your example below
![image](https://user-images.githubusercontent.com/59965498/117559085-49fb2480-b050-11eb-939b-a5a9b9b350fa.png)

Apologies in advance for asking such a basic question, I'm not so familiar with VMD and would really appreciate your help

**Comment by anyuzx** [comment]
hello, the plot you referred to is actually rendered using OVITO. In VMD, it is possible to generate similar plot. However, I don't use script for VMD, the visualization are done by manually select various options. You can check the gif at the end of this notebook [https://github.com/anyuzx/HIPPS-DIMES/blob/main/walkthrough.ipynb](https://github.com/anyuzx/HIPPS-DIMES/blob/main/walkthrough.ipynb).  I also recommend you to read this tutorial https://www.ks.uiuc.edu/Research/vmd/current/ug/node15.html.
