### ISSUE TITLE
Is the entire genome reconstruction feasible?

### ISSUE THREAD

**Issue by Huang-XN** [anyuzx/HIPPS-DIMES#4]
Hi @anyuzx,

Thank you for this wonderful tool. 

In the example, the tutorial showed reconstructing the 3D conformation for only one chromosome using HiC contact map. I was wondering if HIPPS-DIMES could do it for the whole genome instead of one chromosome based on HiC data.   

Thank you. Hope you could answer it.

Best,
Xingnan

**Comment by anyuzx** [comment]
Hi Xingnan, unfortunately, the model has not been tested for reconstructing the multiple chromosomes. If you provide the contact map that contains multiple chromosomes, in principle, the model will generate structures. However, we have not tested whether the reconstructed structures are reasonable or not.

**Comment by Huang-XN** [comment]
Thank you for your reply. I will try it.
